apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-03-05T17:00:37Z"
  name: spring-boot-service
  namespace: default
  resourceVersion: "8456"
  uid: 38235e9e-f7cc-4f50-8a09-7c4c71aab5fb
spec:
  clusterIP: 10.102.170.176
  clusterIPs:
  - 10.102.170.176
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-boot
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
