apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2024-03-05T17:23:04Z"
  generation: 2
  name: spring-boot
  namespace: default
  resourceVersion: "19962"
  uid: 70eb6f4e-3fac-4ecc-9c91-85241c169f0e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: spring-boot
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-boot
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: 10.244.0.70
        - name: DB_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: mysql
        - name: DB_USERNAME
          value: root
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-root-password
              name: my-mysql
        image: himanshuofficial123/spring-boot-application:4.0
        imagePullPolicy: IfNotPresent
        name: spring-boot-container
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-persistent-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-03-05T17:23:05Z"
    lastUpdateTime: "2024-03-05T17:23:05Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-03-05T17:23:04Z"
    lastUpdateTime: "2024-03-06T07:10:49Z"
    message: ReplicaSet "spring-boot-75644589ff" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
